name: Push RT to API
on:
  workflow_dispatch:
  schedule:
    - cron: '*/4 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env: # Or as an environment variable
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        python scrap_data_RT.py
